spring :
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ordersystem
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
  application:
    #    member-service라는 이름으로 eureka에 등록
    name: ordering-service
  kafka:
    kafka-server: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  #  port번호 0으로 지정시 임의숫자값으로 port실행
  port: 0

jwt:
  expiration: 1000
#  ???? ?? 32? ?? ??.(???? ??)
#  beyondaccesstoeknsecretkeybeyondaccesstoeknsecretkeybeyondaccesstoeknsecretkeybeyondaccesstoeknsecretkey
  secretKey: YmV5b25kYWNjZXNzdG9la25zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2VrbnNlY3JldGtleWJleW9uZGFjY2Vzc3RvZWtuc2VjcmV0a2V5YmV5b25kYWNjZXNzdG9la25zZWNyZXRrZXk=
  expirationRT: 288000
#  ???? ?? 32? ?? ??.(???? ??)
#  beyondrefreshsecrettokenkeybeyondrefreshsecrettokenkeybeyondrefreshsecrettokenkey
  secretKeyRT: YmV5b25kcmVmcmVzaHNlY3JldHRva2Vua2V5YmV5b25kcmVmcmVzaHNlY3JldHRva2Vua2V5YmV5b25kcmVmcmVzaHNlY3JldHRva2Vua2V5

